Implement application emojis
Quahu/Disqord pull request #123
Opened 2024-08-05 17:59 UTC by QuantumToasted

## Description

- Implemented the following endpoints:
  - [List Application Emojis](https://discord.com/developers/docs/resources/emoji#list-application-emojis)
  - [Get Application Emoji](https://discord.com/developers/docs/resources/emoji#get-application-emoji)
  - [Create Application Emoji](https://discord.com/developers/docs/resources/emoji#create-application-emoji)
  - [Modify Application Emoji](https://discord.com/developers/docs/resources/emoji#modify-application-emoji)
  - [Delete Application Emoji](https://discord.com/developers/docs/resources/emoji#delete-application-emoji)
- Adds `IApplicationEntity` interface for future-proofing any further entities that can be created, managed, etc. by an application, currently only consumed by `IApplicationEmoji`.

## Checklist

[//]: # "Put an x in [ ] to check the checkbox, e.g. [x]"

- [ ] I discussed this PR with the maintainer(s) prior to opening it.
- [x] I read the [contributing guidelines](https://github.com/Quahu/Disqord/blob/master/.github/CONTRIBUTING.md).
- [x] I tested the changes in this PR.

2024-08-05 23:36 UTC, Quahu requested changes

2024-08-05 23:36 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Emoji/IApplicationEmoji.cs
> +    bool IsManaged { get; }
We'd want to move these to a common interface as these members are duplicated in `IGuildEmoji`

2024-08-05 23:36 UTC, Quahu commented on src/Disqord.Core/Entities/Core/IApplicationEntity.cs
> +public interface IApplicationEntity
```suggestion
public interface IApplicationEntity : IEntity
```

2024-08-06 04:11 UTC, QuantumToasted commented on src/Disqord.Core/Entities/Core/Emoji/IApplicationEmoji.cs
> +    bool IsManaged { get; }
I'm unsure what to name the common interface, as these three properties have pretty much nothing useful in common. I'm open to suggestions, though

2024-08-06 04:15 UTC, QuantumToasted commented on src/Disqord.Core/Entities/Core/IApplicationEntity.cs
> +public interface IApplicationEntity
Resolved in 4870219, was unfamiliar with best practices regarding I*Entity types

2024-08-06 04:28 UTC, QuantumToasted commented on src/Disqord.Core/Entities/Core/Emoji/IApplicationEmoji.cs
> +    bool IsManaged { get; }
These have been abstracted into a new interface in 93d2ee4 -> `IOwnedEmoji`. You're welcome to suggest a better name. I've adjusted XML documentation where appropriate, since `ICustomEmoji` no longer directly implies that it may be owned by a guild or application, but `IOwnedEmoji` can realistically only ever belong to a guild or application.

2025-03-01 08:27 UTC, Quahu approved these changes

2025-03-01 08:28 UTC, merged