Add support for message snapshots (forwarding)
Quahu/Disqord pull request #126
Opened 2024-11-08 18:21 UTC by QuantumToasted

## Description
https://discord.com/developers/docs/resources/message#message-reference-content-attribution-forwards

This PR adds support for receiving and sending message snapshots (forwarded messages).

Notable changes:
- `MessageReferenceType` enum added, with values Reply (0) and Forward (1)
- `IMessageReference` now contains a `MessageReferenceType` Type property
- Added `IMessageSnapshot` interface and Transient implementation - this type is very similar to `IMessage` but lacks an author property. I'm unsure if it would be worth it to abstract common data between the two types further, so I elected not to.
- `MessageJsonModel` is used as the model for snapshots - this introduces a "breaking" change where Author is optional now. Several models were adjusted where Author is known to have a value to simply use `.Value` now.

Received forwarded messages can be found via `IUserMessage#MessageSnapshots`, and can be sent via a LocalMessageReference with Type: Forward (not supported in app command responses)

## Checklist

- [ ] I discussed this PR with the maintainer(s) prior to opening it.
- [x] I read the [contributing guidelines](https://github.com/Quahu/Disqord/blob/master/.github/CONTRIBUTING.md).
- [x] I tested the changes in this PR.

2024-11-10 15:14 UTC, Quahu requested changes

2024-11-10 15:38 UTC, QuantumToasted commented on src/Disqord.Core/Enums/MessageReferenceType.cs
> +    Reply = 0,
Should I leave the XML docs as-is, still? I wanted to make sure consumers of the lib still know that (at least at the moment) this can be used for replies, hence my decision to name the enum value Reply instead of Default.

2024-11-16 20:19 UTC, Quahu commented on src/Disqord.Core/Enums/MessageReferenceType.cs
> +    Reply = 0,
Yeah, they're fine to keep this way

2024-11-16 20:20 UTC, Quahu approved these changes

2024-11-16 20:21 UTC, merged