Guild preview
Quahu/Disqord pull request #21
Opened 2021-07-11 16:16 UTC by shift-eleven

This adds the entities for Guild Previews (interface and transient version) alongside the rest extensions.

2021-07-11 20:52 UTC, Quahu requested changes
Good work, but you ended up with duplicate guild IDs, as the preview model's ID is the guild's ID.

2021-07-11 20:52 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Guild/IGuildPreview.cs
> +    public interface IGuildPreview : IGuildEntity, INamable, ISnowflakeEntity
The interfaces in order should be: `ISnowflakeEntity`, `INamable`.
Remove `IGuildEntity` because the preview's ID is already the guild ID.

2021-07-11 20:52 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Guild/IGuildPreview.cs
> +        ///     Gets the features of this guild.
Gets the features of *the* guild.

2021-07-11 20:52 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Guild/TransientGuildPreview.cs
> +        public Snowflake Id => Model.Id;
With the interface changes, these in order should be: `Id`, `Name`.

2021-07-11 20:52 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Guild/TransientGuildPreview.cs
> +        }
With the interface changes, get rid of the guild ID.

2021-07-12 02:16 UTC, shift-eleven commented on src/Disqord.Core/Entities/Shared/Transient/Guild/TransientGuildPreview.cs
> +        }
Fixed with latest commit

2021-07-12 02:21 UTC, Quahu requested changes

2021-07-12 02:21 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Guild/TransientGuildPreview.cs
> +        }
Empty constructors should have their brackets on the same line with a space inside. You should also get rid of the useless `guildId` parameter.
```cs
public TransientGuildPreview(IClient client, GuildPreviewJsonModel model) 
    : base(client, model)
{ }
```

2021-07-12 02:39 UTC, Quahu approved these changes
Thanks!
(the rest of the changes was based off of feedback in Discord)

2021-07-12 02:40 UTC, merged