Map application commands endpoints
Quahu/Disqord pull request #22
Opened 2021-07-11 16:30 UTC by AnotherZane

2021-07-11 21:21 UTC, Quahu requested changes
Have you tested out all the endpoints? It's a bit difficult to judge if the endpoints and contents are mapped correctly because of Discord's docs.

2021-07-11 21:21 UTC, Quahu commented on src/Disqord.Rest.Api/Routing/Route.Static.cs
> +            public static readonly Route DeleteFollowupMessage = Delete("webhooks/{0:application_id}/{1:interaction_token}/messages/{2:message_id}");
Don't rename these. Response is better, as it's not always going to be a message. E.g. deferred message update in components.

2021-07-11 21:21 UTC, Quahu commented on src/Disqord.Rest.Api/Content/Json/ModifyApplicationCommandPermissionsJsonRestRequestContent.cs
> +        public Optional<Snowflake> Id;
Shouldn't this be required?

2021-07-12 06:34 UTC, AnotherZane commented on src/Disqord.Rest.Api/Routing/Route.Static.cs
> +            public static readonly Route DeleteFollowupMessage = Delete("webhooks/{0:application_id}/{1:interaction_token}/messages/{2:message_id}");
Reverted

2021-07-12 06:36 UTC, AnotherZane commented on src/Disqord.Rest.Api/Content/Json/ModifyApplicationCommandPermissionsJsonRestRequestContent.cs
> +        public Optional<Snowflake> Id;
Discussed in the discord (Needs to be optional as it's reused for another endpoint)

2021-07-19 11:08 UTC, Quahu approved these changes

2021-07-19 11:09 UTC, merged