Added guild templates rest api extensions
Quahu/Disqord pull request #23
Opened 2021-07-11 16:31 UTC by AnotherZane

2021-07-11 16:32 UTC, AnotherZane commented on src/Disqord.Core/Models/GuildTemplateJsonModel.cs
> +        // public GuildJsonModel SerializedSourceGuild;
Probably a good idea to keep this open until a solution to this is found.

2021-07-11 23:40 UTC, Quahu commented on src/Disqord.Core/Models/GuildTemplateJsonModel.cs
> +        // public GuildJsonModel SerializedSourceGuild;
I believe simply exposing the `IJsonObject`, even in the public API/entities, might just be the way to go about it. It's not like the user can do anything useful with the object programmatically anyways, and they can view it easily by just calling `ToString()` which will get them the JSON representation.

2021-07-12 13:29 UTC, AnotherZane commented on src/Disqord.Core/Models/GuildTemplateJsonModel.cs
> +        // public GuildJsonModel SerializedSourceGuild;
I have made it an `IJsonObject` in the recent commits. Maybe we could possibly look into creating an `IGuild` from this by using the `SourceGuildId` as the Id?

2021-07-13 00:09 UTC, Quahu requested changes
Could you also add the entity extensions for manipulating the template entities? `template.DeleteAsync()` and so on.

2021-07-13 00:09 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Guild/IGuildTemplate.cs
> +        IJsonObject SerializedSourceGuild { get; }
This should be just `SerializedGuild`.

2021-07-13 00:09 UTC, Quahu commented on src/Disqord.Rest/Extensions/Entity/RestEntityExtensions.Guild.cs
> +        }
This is a global method, it shouldn't be on the guild object.

2021-07-13 00:09 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Guild/IGuildTemplate.cs
> +        ///     Gets the creator ID of the template.
"Gets the ID of the creator of this template."

2021-07-13 00:09 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Guild/IGuildTemplate.cs
> +        int UsageCount { get; }
I say we call this `Uses`, to match how the property is called on invites.

2021-07-13 07:02 UTC, Quahu approved these changes

2021-07-14 02:39 UTC, merged