Implement REST endpoints related to threads
Quahu/Disqord pull request #26
Opened 2021-07-12 20:51 UTC by Zackattak01

2021-07-12 21:52 UTC, Quahu requested changes

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest.Api/Methods/RestApiClientExtensions.Channel.cs
> +        public static Task AddThreadMemberAsync(this IRestApiClient client, Snowflake threadId, Snowflake userId, IRestRequestOptions options = null)
`userId` -> `memberId`

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest.Api/Methods/RestApiClientExtensions.Channel.cs
> +        public static Task RemoveThreadMemberAsync(this IRestApiClient client, Snowflake threadId, Snowflake userId, IRestRequestOptions options = null)
`userId` -> `memberId`

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/Channel/ModifyThreadChannelActionProperties.cs
> +            set => throw new InvalidOperationException("Thread channels do not support overwrites");
`Thread channels do not support modifying overwrites. Modify the parent channel's overwrites instead.`

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/Channel/ModifyThreadChannelActionProperties.cs
> +            set => throw new InvalidOperationException("Thread channels do not support position");
`Thread channels do not support modifying positions.`

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/Channel/ModifyThreadChannelActionProperties.cs
> +        public override Optional<int> Position
Apply `[EditorBrowsable(EditorBrowsableState.Never)]` to the property.

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/Channel/ModifyThreadChannelActionProperties.cs
> +        public override Optional<IEnumerable<LocalOverwrite>> Overwrites
Apply `[EditorBrowsable(EditorBrowsableState.Never)]` to the property.

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/Channel/ModifyThreadChannelActionProperties.cs
> +        public Optional<int> Slowmode { internal get; set; }
I think this should be moved to a common base between for the text and thread channels, i.e. `ModifyMessageGuildChannelActionProperties`. This should also be a TimeSpan which is then converted to minutes by the lib.

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/Channel/ModifyThreadChannelActionProperties.cs
> +        public Optional<int> AutoArchiveDuration { internal get; set; }
AutomaticArchiveDuration, should be a TimeSpan.

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        public static async Task<IThreadChannel> CreatePublicThreadAsync(this IRestClient client, Snowflake channelId, string name, Snowflake? messageId = null, TimeSpan autoArchiveDuration = default
`automaticArchiveDuration`. Should this be nullable?

2021-07-12 21:52 UTC, Quahu commented on src/Disqord.Rest.Api/Content/Json/CreateThreadJsonRestRequestContent.cs
> +        public Optional<int?> Type;
This is only optional, not nullable. You can change it to `Optional<ChannelType>` instead.

2021-07-12 22:07 UTC, Quahu requested changes

2021-07-12 22:07 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        internal static async Task<(bool HasMore, IReadOnlyList<IThreadChannel> Threads)> InternalFetchJoinedPrivateArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, Snow
The internal fetch methods should appear their public equivalents.

2021-07-12 22:07 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +            => new PagedEnumerable<IThreadChannel>(new FetchJoinedPrivateArchivedThreadsPagedEnumerator(client, channelId, limit, startFromId, options));
Missing newline after the method.

2021-07-12 22:07 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +            => new PagedEnumerable<IThreadChannel>(new FetchArchivedThreadsPagedEnumerator(client, channelId, limit, startFromDate, false, options));
Missing newline after the method.

2021-07-12 22:07 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        internal static async Task<(bool HasMore, IReadOnlyList<IThreadChannel> Threads)> InternalFetchPrivateArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, DateTimeOf
The internal fetch methods should appear their public equivalents.

2021-07-12 22:07 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +            => new PagedEnumerable<IThreadChannel>(new FetchArchivedThreadsPagedEnumerator(client, channelId, limit, startFromDate, true, options));
Missing newline after the method.

2021-07-12 22:07 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        internal static async Task<(bool HasMore, IReadOnlyList<IThreadChannel> Threads)> InternalFetchPublicArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, DateTimeOff
The internal fetch methods should appear their public equivalents.

2021-07-12 22:11 UTC, Quahu commented on src/Disqord.Rest/Requests/Pagination/Implementation/FetchArchivedThreadsPagedEnumerator.cs
> +                await Client.InternalFetchPrivateArchivedThreads(_channelId, NextAmount, startFromTime, options).ConfigureAwait(false);
Reformat this to:
```cs
var task = _enumeratePublicThreads
    ? Client.InternalFetchPublicArchivedThreads(_channelId, NextAmount, startFromTime, options)
    : Client.InternalFetchPrivateArchivedThreads(_channelId, NextAmount, startFromTime, options);
var response = await task.ConfigureAwait(false);
```

2021-07-12 23:20 UTC, Quahu requested changes

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/Channel/ModifyThreadChannelActionProperties.cs
> +            set => throw new InvalidOperationException("Thread channels do not support modifying the category id. Modify the parent channel's category id instead.");
ID in the exception message should be capitalized.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/Channel/ModifyThreadChannelActionProperties.cs
> +        public Optional<TimeSpan> AutoArchiveDuration { internal get; set; }
You did not rename the property to `AutomaticArchiveDuration`.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/Entity/RestEntityExtensions.Channel.cs
> +        public static Task<IReadOnlyList<IThreadMember>> FetchMembers(this IThreadChannel thread, IRestRequestOptions options = null)
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/Entity/RestEntityExtensions.Channel.cs
> +        public static Task<IReadOnlyList<IThreadChannel>> FetchActiveThreads(this ITextChannel channel, IRestRequestOptions options = null)
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/Entity/RestEntityExtensions.Channel.cs
> +        public static Task<IReadOnlyList<IThreadChannel>> FetchPublicArchivedThreads(this IThreadChannel channel, int limit = 100, DateTimeOffset? startFromDate = null, IRestRequestOptions options =
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/Entity/RestEntityExtensions.Channel.cs
> +        public static Task<IReadOnlyList<IThreadChannel>> FetchPrivateArchivedThreads(this IThreadChannel channel, int limit = 100, DateTimeOffset? startFromDate = null, IRestRequestOptions options =
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/Entity/RestEntityExtensions.Channel.cs
> +        public static Task<IReadOnlyList<IThreadChannel>> FetchJoinedPrivateArchivedThreads(this IThreadChannel channel, int limit = 100, Snowflake? startFromId = null, IRestRequestOptions options =
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +                    content.RateLimitPerUser = Optional.Convert(messageGuildChannelProperties.Slowmode, x => (int)x.TotalMinutes);
This is wrong, the slowmode is in seconds.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        public static async Task<IReadOnlyList<IThreadMember>> FetchThreadMembers(this IRestClient client, Snowflake threadId, IRestRequestOptions options = null)
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        public static async Task<IReadOnlyList<IThreadChannel>> FetchActiveThreads(this IRestClient client, Snowflake channelId, IRestRequestOptions options = null)
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        public static async Task<IReadOnlyList<IThreadChannel>> FetchPublicArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, DateTimeOffset? startFromDate = null, IRestRe
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        public static async Task<IReadOnlyList<IThreadChannel>> FetchPrivateArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, DateTimeOffset? startFromDate = null, IRestR
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        internal static async Task<(bool HasMore, IReadOnlyList<IThreadChannel> Threads)> InternalFetchPrivateArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, DateTimeOf
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        internal static async Task<(bool HasMore, IReadOnlyList<IThreadChannel> Threads)> InternalFetchPublicArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, DateTimeOff
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        public static async Task<IReadOnlyList<IThreadChannel>> FetchJoinedPrivateArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, Snowflake? startFromId = null, IRestRe
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        internal static async Task<(bool HasMore, IReadOnlyList<IThreadChannel> Threads)> InternalFetchJoinedPrivateArchivedThreads(this IRestClient client, Snowflake channelId, int limit = 100, Snow
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest.Api/Methods/RestApiClientExtensions.Channel.cs
> +        public static Task<ThreadMemberJsonModel[]> FetchThreadMembers(this IRestApiClient client, Snowflake threadId, IRestRequestOptions options = null)
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest.Api/Methods/RestApiClientExtensions.Channel.cs
> +        public static Task<ThreadListJsonModel> FetchPublicArchivedThreads(this IRestApiClient client, Snowflake channelId, int limit = 100, DateTimeOffset? startFromDate = null, IRestRequestOptions
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest.Api/Methods/RestApiClientExtensions.Channel.cs
> +        public static Task<ThreadListJsonModel> FetchPrivateArchivedThreads(this IRestApiClient client, Snowflake channelId, int limit = 100, DateTimeOffset? startFromDate = null, IRestRequestOptions
Missing Async method suffix.

2021-07-12 23:20 UTC, Quahu commented on src/Disqord.Rest.Api/Methods/RestApiClientExtensions.Channel.cs
> +        public static Task<ThreadListJsonModel> FetchJoinedPrivateArchivedThreads(this IRestApiClient client, Snowflake channelId, int limit = 100, Snowflake? startFromId = null, IRestRequestOptions
Missing Async method suffix.

2021-07-13 07:03 UTC, Quahu approved these changes

2021-07-18 06:57 UTC, Quahu requested changes

2021-07-18 06:57 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +                AutoArchiveDuration = Optional.Conditional(automaticArchiveDuration != null, (int)automaticArchiveDuration.Value.TotalMinutes),
This will throw if the duration isn't provided, you need the lambda like in the method above.
The cast should have a space after it.

2021-07-18 06:57 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +                AutoArchiveDuration = Optional.Conditional(automaticArchiveDuration != null, duration => (int)duration.Value.TotalMinutes, automaticArchiveDuration),
The cast should have a space after it.

2021-07-18 06:57 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +                    content.RateLimitPerUser = Optional.Convert(messageGuildChannelProperties.Slowmode, x => (int)x.TotalSeconds);
The cast needs a space after it.

2021-07-18 06:57 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +
👁️ 👁️

2021-07-18 06:57 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +                        content.AutoArchiveDuration = Optional.Convert(threadProperties.AutomaticArchiveDuration, x => (int)x.TotalMinutes);
The cast needs a space after it.

2021-07-27 04:59 UTC, AnotherZane approved these changes

2021-08-05 11:47 UTC, AnotherZane commented
LGTM!

2021-08-05 11:48 UTC, Quahu approved these changes

2021-08-05 11:49 UTC, merged