Get Followup Message endpoint
Quahu/Disqord pull request #37
Opened 2021-07-31 08:24 UTC by AnotherZane

## Description

Added `Get Followup Message` endpoint and related extension methods.

## Checklist

- [x] I discussed this PR with the maintainer(s) prior to opening it.
- [x] I read the [contributing guidelines](./.github/CONTRIBUTING.md).
- [ ] I tested the changes in this PR.

2021-07-31 19:59 UTC, Quahu requested changes

2021-07-31 19:59 UTC, Quahu commented on src/Disqord.Rest.Api/Content/Json/CreateFollowupInteractionResponseJsonRestRequestContent.cs
> +    public class CreateFollowupInteractionResponseJsonRestRequestContent : ExecuteWebhookJsonRestRequestContent
Name is not consistent with the API method's name.

2021-07-31 19:59 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Interactions.cs
> +            var model = await client.ApiClient.FetchFollowupInteractionResponseAsync(applicationId, interactionToken, messageId, options).ConfigureAwait(false);
What about those ephemeral messages we've talked about?
Either way, this should be catching 404s with the respective code and return null instead of throwing.

2021-07-31 19:59 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Interactions.cs
> +                Flags = followup.Flags,
Flags go at the end.

2021-08-01 13:01 UTC, AnotherZane commented
Made requested changes.

2021-08-01 19:50 UTC, Quahu approved these changes

2021-08-05 11:32 UTC, merged