Added guild events
Quahu/Disqord pull request #56
Opened 2021-08-22 13:56 UTC by shift-eleven

## Description

Implements the new guild events.

## Checklist

- [x] I discussed this PR with the maintainer(s) prior to opening it.
- [x] I read the [contributing guidelines](./.github/CONTRIBUTING.md).
- [ ] I tested the changes in this PR.

2021-08-22 17:43 UTC, Quahu requested changes

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Guild/TransientGuildEvent.cs
> +        public int UserCount => Model.UserCount.GetValueOrDefault();
```suggestion
        public int? UserCount => Model.UserCount.GetValueOrNullable();
```

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Guild/IGuildEvent.cs
> +        IGuildEventMetadata Metadata { get; }
We probably want to flatten this just like thread metadata?
Also see the comment attached to `GuildScheduledEventEntityType`.

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Rest.Api/Routing/Route.Static.cs
> +            public static readonly Route GetGuildEvents = Get("guilds/{0:guild_id}/events");
You can remove the redundant `Guild` from the routes.
```suggestion
            public static readonly Route GetEvents = Get("guilds/{0:guild_id}/events");
```

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Modify/ModifyGuildEventActionProperties.cs
> +    public class ModifyGuildEventActionProperties
Inconsistent with all other action properties, the members must be properties with appropriate accessors.

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.GuildEvents.cs
> +            return models.ToReadOnlyList(x => new TransientGuildEvent(client, x));
Closure allocation.

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Guild/TransientGuildEvent.cs
> +        public GuildScheduledEventEntityType Status => Model.Status;
```suggestion
        public GuildScheduledEventStatus Status => Model.Status;
```

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Guild/TransientGuildEvent.cs
> +        public GuildScheduledEventStatus EntityType => Model.EntityType;
```suggestion
        public GuildScheduledEventEntityType EntityType => Model.EntityType;
```

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Core/Enums/GuildScheduledEventEntityType.cs
> +    public enum GuildScheduledEventEntityType : byte
Target might be preferred?
Additionally, based on how many more fields will be added to the metadata it might be preferable to have different guild event types, i.e. like we do with interactions.
`speaker_ids` will only be provided if the entity type is a stage.

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Core/Enums/GuildScheduledEventEntityType.cs
> +        StageInstance,
To be consistent with the lib's naming.
```suggestion
        Stage,
```

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Guild/TransientGuildEvent.cs
> +        /// <inheritdoc/>
```suggestion
        public Snowflake? ChannelId => Model.ChannelId;

        /// <inheritdoc/>
```

2021-08-22 17:43 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Guild/IGuildEvent.cs
> +        int UserCount { get; }
`MemberCount`?

Not sure what the external entity type means, so I don't know if this change would make sense.

2021-08-22 17:49 UTC, AnotherZane commented on src/Disqord.Core/Entities/Core/Guild/IGuildEvent.cs
> +        int UserCount { get; }
It might be possible that non members can subscribe to events as they can be public. Will need to confirm this when more info about the feature is released.

2021-08-22 18:24 UTC, AnotherZane requested changes
The enum naming changes would make more sense, also suggested them on the [discord docs](https://github.com/discord/discord-api-docs/pull/3586#pullrequestreview-735598543).

Also please add a new line to the end of all changed/new files.

2021-08-22 18:24 UTC, AnotherZane commented on src/Disqord.Core/Enums/GuildScheduledEventEntityType.cs
> +    public enum GuildScheduledEventEntityType : byte
```suggestion
    public enum GuildEventEntityType : byte
```

or 

```suggestion
    public enum GuildEventTarget : byte
```

2021-08-22 18:24 UTC, AnotherZane commented on src/Disqord.Core/Enums/GuildScheduledEventStatus.cs
> +    public enum GuildScheduledEventStatus : byte
```suggestion
    public enum GuildEventStatus : byte
```

2021-08-23 05:52 UTC, AnotherZane commented
On another note, the `StagePrivacyLevel` enum could use a rename as it's no longer only used to denote the privacy level of a stage. Not sure what it can be changed to tho, `PrivacyLevel` by itself is too vague.

2021-08-23 15:59 UTC, shift-eleven commented on src/Disqord.Core/Enums/GuildScheduledEventEntityType.cs
> +    public enum GuildScheduledEventEntityType : byte
Changed to `GuildEventTarget`

2022-01-24 09:45 UTC, merged