feature: rest endpoints for application commands
Quahu/Disqord pull request #58
Opened 2021-09-03 15:25 UTC by Neuheit

## Description

Implements the main rest endpoints for slash commands.

## Checklist

[//]: # "Put an x in [ ] to check the checkbox, e.g. [x]"

- [x] I discussed this PR with the maintainer(s) prior to opening it.
- [x] I read the [contributing guidelines](./.github/CONTRIBUTING.md).
- [ ] I tested the changes in this PR.

Testing will come soon.

2021-09-10 18:56 UTC, AnotherZane requested changes
I've added comments where some changes should be made.

Furthermore:
- The rest entity extensions for application commands need to be added.
- The implementation of interfaces in transient entities should preferably implement members inherited by the interface, followed by the members in the interface itself.

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Core/Entities/Local/ApplicationCommands/LocalApplicationCommand.cs
> +        public void Validate()
The number of options provided should be validated here as well.

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Core/Entities/Local/ApplicationCommands/LocalApplicationCommand.cs
> +    public class LocalApplicationCommand : ILocalConstruct
Currently, the application command's type cannot be specified. This needs to be implemented.

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Core/Entities/Local/ApplicationCommands/LocalApplicationCommandOption.cs
> +        public void Validate()
The number of options and choices provided should be validated here as well. I'm not sure if setting the `MaxChoiceSize` for the list of choices in the constructor above is required.

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Core/Entities/Local/ApplicationCommands/LocalApplicationCommandOptionChoice.cs
> +        public static readonly Type[] AllowedTypes = { typeof(string), typeof(int), typeof(double) };
This array can still be modified, it should be made read-only (Eg. `new[] {}.ReadOnly()`). This was an oversight on my part as well during my previous review.

This might also need to be made private.

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Core/Entities/Core/Interactions/Commands/IApplicationCommand.cs
> +        ApplicationCommandType? Type { get; }
I think this does not have to be nullable, we can default to a slash command if a type is not provided as mentioned in the API docs.

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Core/Entities/Shared/Transient/Interactions/Commands/TransientApplicationCommand.cs
> +        public ApplicationCommandType? Type => Model.Type.GetValueOrNullable();
We can default to a slash command here.

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Core/Entities/Shared/Transient/Interactions/Commands/TransientApplicationCommand.cs
> +        public bool? IsEnabledByDefault => Model.DefaultPermission.GetValueOrNullable();
```suggestion
        public bool IsEnabledByDefault => Model.DefaultPermission.GetValueOrDefault();
```

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Core/Entities/Shared/Transient/Interactions/Commands/TransientApplicationCommandOption.cs
> +        public bool? Required => Model.Required.GetValueOrNullable();
```suggestion
        public bool Required => Model.Required.GetValueOrDefault();
```

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Rest/Extensions/RestClientExtensions.ApplicationCommands.cs
> +        public static async Task<IApplicationCommand> CreateGlobalApplicationCommandAsync(this IRestClient client, Snowflake applicationId, string name, string description, Action<CreateApplicationCo
This method should take a `LocalApplicationCommand` as a parameter instead.

2021-09-10 18:56 UTC, AnotherZane commented on src/Disqord.Rest/Extensions/RestClientExtensions.ApplicationCommands.cs
> +        public static async Task<IApplicationCommand> CreateGuildApplicationCommandAsync(this IRestClient client, Snowflake applicationId, Snowflake guildId, string name, string description, Action<C
This method should take a `LocalApplicationCommand` as a parameter instead.

2021-09-20 23:53 UTC, Neuheit commented
Closing in favor of #60

2021-09-20 23:53 UTC, closed without merging