Add Type 11(Attachment) to SlashCommandOptionType
Quahu/Disqord pull request #74
Opened 2021-12-19 21:00 UTC by n-Ultima

## Description

Added the `Attachment` option to SlashCommandOptionType.

## Checklist

[//]: # "Put an x in [ ] to check the checkbox, e.g. [x]"

- [ ] I discussed this PR with the maintainer(s) prior to opening it.
- [x] I read the [contributing guidelines](https://github.com/Quahu/Disqord/blob/master/.github/CONTRIBUTING.md).
- [x] I tested the changes in this PR.

2021-12-19 21:29 UTC, n-Ultima commented
Worth noting that at the time of writing, this is still pending in the discord docs, and the frontend is non existent.

2021-12-20 14:27 UTC, AnotherZane approved these changes

2021-12-27 11:53 UTC, Quahu requested changes

2021-12-27 11:53 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Interactions/Commands/TransientApplicationCommandInteractionEntities.cs
> +                return _attachments ??= Model.Attachments.Value.ToReadOnlyDictionary(
Add a newline between the returns.

2021-12-27 11:53 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Interactions/Commands/TransientApplicationCommandInteractionEntities.cs
> +
Remove this newline.

2021-12-27 17:45 UTC, n-Ultima commented on src/Disqord.Core/Entities/Shared/Transient/Interactions/Commands/TransientApplicationCommandInteractionEntities.cs
> +                return _attachments ??= Model.Attachments.Value.ToReadOnlyDictionary(
Done in latest commit.

2021-12-27 17:45 UTC, n-Ultima commented on src/Disqord.Core/Entities/Shared/Transient/Interactions/Commands/TransientApplicationCommandInteractionEntities.cs
> +
Done in latest commit.

2021-12-28 17:07 UTC, merged