Minor channels overhaul, implemented forum channels, text in voice
Quahu/Disqord pull request #94
Opened 2022-06-02 16:20 UTC by AnotherZane

## Description

- Implemented forum channels
- Removed store channels
- Added some docstrings
- Implemented text in voice
- Updated voice channel permissions
- Implemented missing rest method to create stage channels
- Changed some other channel related stuff (transient group channel, added missing properties, etc)

(pr base will be moved to master branch once bot-rewrite is merged)

## Checklist

- [x] I discussed this PR with the maintainer(s) prior to opening it.
- [x] I read the [contributing guidelines](https://github.com/Quahu/Disqord/blob/master/.github/CONTRIBUTING.md).
- [x] I tested the changes in this PR.

2022-06-03 02:35 UTC, Quahu requested changes

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/IForumChannel.cs
> +        ///     Gets the ID of the last thread made in this channel.
```suggestion
        ///     Gets the ID of the last thread created in this channel.
```

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Core/Enums/ChannelFlag.cs
> +        ///     The thread channel is pinned to the top of it's parent forum channel.
```suggestion
        ///     The thread channel is pinned to the top of its parent forum channel.
```

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Channels/Common/TransientChannel.cs
> +            return null;
Are we not implementing unknown channels?

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Channels/Guild/TransientForumChannel.cs
> +        public TimeSpan DefaultAutomaticArchiveDuration => TimeSpan.FromMinutes(Model.DefaultAutoArchiveDuration.GetValueOrDefault(1400));
```suggestion
        public TimeSpan DefaultAutomaticArchiveDuration => TimeSpan.FromMinutes(Model.DefaultAutoArchiveDuration.GetValueOrDefault(1440));
```

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Channels/Guild/TransientTextChannel.cs
> +        public TimeSpan DefaultAutomaticArchiveDuration => TimeSpan.FromMinutes(Model.DefaultAutoArchiveDuration.GetValueOrDefault(1400));
```suggestion
        public TimeSpan DefaultAutomaticArchiveDuration => TimeSpan.FromMinutes(Model.DefaultAutoArchiveDuration.GetValueOrDefault(1440));

```

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Bot/Bot/Base/Setup/DiscordBotBase.Setup.cs
> -        typeParserProvider.AddParser(new GuildChannelTypeParser<IStoreChannel>());
Deprecation instead?

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Channels/Common/TransientChannel.cs
> -                case ChannelType.Store:
Deprecation instead?

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Core/Entities/Shared/Transient/Channels/Guild/Common/TransientGuildChannel.cs
> -
Deprecation instead?

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Core/Enums/ChannelType.cs
> -
Deprecation instead?

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Gateway/Entities/Cached/Channels/Common/CachedChannel.cs
> +            // Text channels can be changed to changed to News channels and vice-versa
```suggestion
            // Text channels can be changed to news channels and vice-versa.
```

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Gateway/Entities/Cached/Channels/Guild/CachedForumChannel.cs
> +                DefaultAutomaticArchiveDuration = TimeSpan.FromMinutes(model.DefaultAutoArchiveDuration.Value);
The default values being set for the transient variants don't match this, where here it's unspecified.

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Gateway/Entities/Cached/Channels/Guild/Common/CachedGuildChannel.cs
> -
Deprecation instead?

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Rest.Api/Content/Json/CreateGuildChannelJsonRestRequestContent.cs
> -        }
Is the name no longer required or is this an oversight?

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Rest.Api/Routing/Route.Static.cs
> +            public static readonly Route StartThreadInForum = Post("channels/{0:channel_id}/threads");
```suggestion
            public static readonly Route StartForumThread = Post("channels/{0:channel_id}/threads");

```

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Create/Channel/CreatePrivateThreadChannelActionProperties.cs
> +        public Optional<bool> Invitable { internal get; set; }
```suggestion
        public Optional<bool> AllowsInvitation { internal get; set; }
```
Be consistent with the [existing property names](https://github.com/Quahu/Disqord/blob/bot-rewrite/src/Disqord.Core/Entities/Core/Channels/Guild/Threads/IThreadMetadata.cs#L37).

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Rest/ActionProperties/Create/Channel/CreatePrivateThreadChannelActionProperties.cs
> +    }
Missing internal ctor.

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Rest/Extensions/RestClientExtensions.Channel.cs
> +        public static async Task<IThreadChannel> CreateForumPostAsync(this IRestClient client,
```suggestion
        public static async Task<IThreadChannel> CreateForumThreadAsync(this IRestClient client,
```

2022-06-03 02:35 UTC, Quahu commented on src/Disqord.Rest/Extensions/Entity/RestEntityExtensions.Channel.cs
> +        public static Task<IThreadChannel> CreatePostAsync(this IForumChannel channel,
```suggestion
        public static Task<IThreadChannel> CreateThreadAsync(this IForumChannel channel,
```

2022-06-03 02:37 UTC, AnotherZane commented on src/Disqord.Core/Entities/Shared/Transient/Channels/Common/TransientChannel.cs
> +            return null;
Not really needed since the only unknown channels bot can come across are in guilds, eg. Directory, etc

2022-06-03 04:10 UTC, AnotherZane commented
Not using deprecation for store channels as they have been removed from the API.

2022-07-05 18:39 UTC, Quahu requested changes

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Bot/Commands/Checks/RequireAgeRestrictedAttribute.cs
> +        return Results.Failure("This can only be executed in an age restricted channel.");
```suggestion
        return Results.Failure("This can only be executed in an age-restricted channel.");

```

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/Common/IAgeRestrictableChannel.cs
> +    ///     Gets whether this channel is age restricted.
```suggestion
    ///     Gets whether this channel is age-restricted.
```

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/Common/IAgeRestrictableChannel.cs
> +public interface IAgeRestrictableChannel : ICategorizableGuildChannel
xmldocs

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/Common/ISlowmodeChannel.cs
> +public interface ISlowmodeChannel : IGuildChannel
xmldocs

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/Common/IThreadParentChannel.cs
> +public interface IThreadParentChannel : IAgeRestrictableChannel
xmldocs, inheritance

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/Common/ITopicChannel.cs
> +public interface ITopicChannel : IGuildChannel
xmldocs

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/Common/IMessageGuildChannel.cs
> +    public interface IMessageGuildChannel : ISlowmodeChannel, IMessageChannel, ITaggableEntity
```suggestion
    public interface IMessageGuildChannel : IMessageChannel, ISlowmodeChannel, ITaggableEntity

```

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/IForumChannel.cs
> +    public interface IForumChannel : ITopicChannel, IThreadParentChannel, ISlowmodeChannel
```suggestion
    public interface IForumChannel : IThreadParentChannel, ITopicChannel, ISlowmodeChannel
```

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/ITextChannel.cs
> +    public interface ITextChannel : ITopicChannel, IThreadParentChannel, IMessageGuildChannel
```suggestion
    public interface ITextChannel : IMessageGuildChannel, IThreadParentChannel, ITopicChannel,

```

2022-07-05 18:39 UTC, Quahu commented on src/Disqord.Core/Entities/Core/Channels/Guild/IVoiceChannel.cs
> +    public interface IVoiceChannel : IAgeRestrictableChannel, IVocalGuildChannel, IMessageGuildChannel
```suggestion
    public interface IVoiceChannel : IVocalGuildChannel, IMessageGuildChannel, IAgeRestrictableChannel

```

2022-07-09 11:09 UTC, Quahu approved these changes

2022-07-09 11:09 UTC, merged